/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class stereolab_CUDADiff */

#ifndef _Included_stereolab_CUDADiff
#define _Included_stereolab_CUDADiff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     stereolab_CUDADiff
 * Method:    doCalculationNative
 * Signature: ([[B[[BIIIZZI[[I[[Z)V
 */
JNIEXPORT void JNICALL Java_stereolab_CUDADiff_doCalculationNative
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jint, jint, jint, jboolean, jboolean, jint, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
