/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class stereolab_CUDADistribDiff */

#ifndef _Included_stereolab_CUDADistribDiff
#define _Included_stereolab_CUDADistribDiff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     stereolab_CUDADistribDiff
 * Method:    doCalculationNative
 * Signature: ([[B[[BIIIZZI[[I[[Z)V
 */
JNIEXPORT void JNICALL Java_stereolab_CUDADistribDiff_doCalculationNative
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jint, jint, jint, jboolean, jboolean, jint, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
